import { existsSync, mkdirSync, readdirSync, readFileSync, renameSync, rmSync, statSync, writeFileSync, cpSync } from 'node:fs';
import path from 'node:path';
import { spawnSync } from 'node:child_process';

export type ArmFailureType = 'FAILED_READ' | 'FAILED_ENCODE' | 'FAILED_VERIFY' | 'FAILED_FINALIZE' | 'FAILED_METADATA' | 'FAILED_INTERRUPTED' | 'CANCELLED' | 'UNKNOWN_ERROR';

export interface TrackExpectation { discId?: string; expectedTracks: number; }
export interface JobPaths { workDir: string; stagingDir: string; publishDir: string; logDir: string; wavDir: string; abcdeConfig: string; stdoutLog: string; stderrLog: string; }
export interface ValidationResult { ok: boolean; failureType?: ArmFailureType; error?: string; flacFiles: string[]; expectedTracks: number; completedTracks: number; }
export interface ClassifiedAbcdeFailure { failureType: ArmFailureType; reason: string; }
interface PersistedMusicBrainzMetadata { discNumber?: number; totalDiscs?: number; musicBrainzDiscId?: string; releaseId?: string; releaseDate?: string; }
interface PersistedJobMetadata { musicBrainz?: PersistedMusicBrainzMetadata; }

export function createJobPaths(workRoot: string, jobId: string): JobPaths {
  const safeJobId = jobId.replace(/[^a-zA-Z0-9_-]/g, '');
  const workDir = path.join(workRoot, safeJobId);
  return {
    workDir,
    stagingDir: path.join(workDir, 'staging'),
    publishDir: path.join(workDir, 'publish'),
    logDir: path.join(workDir, 'logs'),
    wavDir: path.join(workDir, 'wav'),
    abcdeConfig: path.join(workDir, 'abcde.conf'),
    stdoutLog: path.join(workDir, 'logs', 'abcde.stdout.log'),
    stderrLog: path.join(workDir, 'logs', 'abcde.stderr.log'),
  };
}

export function prepareFreshJob(paths: JobPaths): void {
  rmSync(paths.workDir, { recursive: true, force: true });
  mkdirSync(paths.stagingDir, { recursive: true });
  mkdirSync(paths.publishDir, { recursive: true });
  mkdirSync(paths.logDir, { recursive: true });
  mkdirSync(paths.wavDir, { recursive: true });
}

export function readTrackExpectation(device: string): TrackExpectation {
  const result = spawnSync('cd-discid', [device], { encoding: 'utf8', timeout: 5000 });
  if (result.status !== 0) return { expectedTracks: 0 };
  const parts = result.stdout.trim().split(/\s+/);
  const discId = parts[0] && /^[a-fA-F0-9]+$/.test(parts[0]) ? parts[0].toLowerCase() : undefined;
  const expectedTracks = parts[1] ? Number(parts[1]) : 0;
  return { ...(discId ? { discId } : {}), expectedTracks: Number.isFinite(expectedTracks) ? expectedTracks : 0 };
}

export function writeArmAbcdeConfig(paths: JobPaths, outputFormat: string): void {
  if (outputFormat.toLowerCase() !== 'flac') throw new Error('ARM-style audio pipeline only supports FLAC output');
  const config = [
    '# Generated by Rippymcripface for an isolated ARM-style audio job.',
    'CDDBMETHOD=musicbrainz',
    'INTERACTIVE=n',
    'CDDBLOCALRECURSIVE=n',
    'NOSUBMIT=y',
    'CDROMREADERSYNTAX=cdparanoia',
    'CDPARANOIA=cdparanoia',
    'CDDISCID=cd-discid',
    'OUTPUTTYPE=flac',
    'FLACENCODERSYNTAX=flac',
    'FLAC=flac',
    'PADTRACKS=y',
    'MAXPROCS=2',
    'ACTIONS=musicbrainz,read,encode,tag,move,clean',
    'CDPARANOIAOPTS="-z=100 -X"',
    'FLACOPTS="-8 -V"',
    `OUTPUTDIR=${shellQuote(paths.stagingDir)}`,
    `WAVOUTPUTDIR=${shellQuote(paths.wavDir)}`,
    "OUTPUTFORMAT='${ARTISTFILE}/${ALBUMFILE}/${TRACKNUM} - ${TRACKFILE}'",
    "VAOUTPUTFORMAT='Various Artists/${ALBUMFILE}/${TRACKNUM} - ${ARTISTFILE} - ${TRACKFILE}'",
    'ONETRACKOUTPUTFORMAT=$OUTPUTFORMAT',
    'VAONETRACKOUTPUTFORMAT=$VAOUTPUTFORMAT',
    '',
  ].join('\n');
  writeFileSync(paths.abcdeConfig, config, { encoding: 'utf8', mode: 0o600 });
}

function shellQuote(value: string): string { return `'${value.replace(/'/g, `'\\''`)}'`; }

export function listFiles(root: string, ext: string): string[] {
  if (!existsSync(root)) return [];
  const out: string[] = [];
  const walk = (dir: string): void => {
    for (const entry of readdirSync(dir)) {
      const full = path.join(dir, entry);
      const st = statSync(full);
      if (st.isDirectory()) walk(full);
      else if (st.isFile() && full.toLowerCase().endsWith(ext)) out.push(full);
    }
  };
  walk(root);
  return out.sort();
}

export function verifyFlac(file: string): boolean {
  const result = spawnSync('flac', ['-t', '-s', file], { encoding: 'utf8', timeout: 120_000 });
  return result.status === 0;
}

export function applyMusicBrainzDiscMetadata(paths: JobPaths): void {
  const metadata = readPersistedJobMetadata(paths);
  const mb = metadata.musicBrainz;
  if (!mb?.discNumber) return;
  const args = [`--set-tag=DISCNUMBER=${mb.discNumber}`];
  if (mb.totalDiscs) args.push(`--set-tag=DISCTOTAL=${mb.totalDiscs}`);
  if (mb.musicBrainzDiscId) args.push(`--set-tag=MUSICBRAINZ_DISCID=${mb.musicBrainzDiscId}`);
  if (mb.releaseId) args.push(`--set-tag=MUSICBRAINZ_ALBUMID=${mb.releaseId}`);
  if (mb.releaseDate) args.push(`--set-tag=DATE=${mb.releaseDate}`);
  for (const file of listFiles(paths.stagingDir, '.flac')) {
    const result = spawnSync('metaflac', [...args, file], { encoding: 'utf8', timeout: 120_000 });
    if (result.status !== 0) throw new Error(`metaflac failed for ${path.basename(file)}: ${result.stderr || result.stdout || result.error?.message || 'unknown error'}`);
  }
}

export function validateCompletedRip(paths: JobPaths, expectedTracks: number, abcdeExitCode: number | null): ValidationResult {
  const flacFiles = listFiles(paths.stagingDir, '.flac');
  if (abcdeExitCode !== 0) {
    const classified = classifyAbcdeFailure(paths);
    return { ok: false, failureType: classified.failureType, error: `${classified.reason}; abcde exited with code ${abcdeExitCode}`, flacFiles, expectedTracks, completedTracks: flacFiles.length };
  }
  if (expectedTracks <= 0) return { ok: false, failureType: 'FAILED_METADATA', error: 'could not determine expected audio track count', flacFiles, expectedTracks, completedTracks: flacFiles.length };
  if (flacFiles.length !== expectedTracks) return { ok: false, failureType: 'FAILED_VERIFY', error: `expected ${expectedTracks} FLAC files but found ${flacFiles.length}`, flacFiles, expectedTracks, completedTracks: flacFiles.length };
  const bad = flacFiles.find((file) => !verifyFlac(file));
  if (bad) return { ok: false, failureType: 'FAILED_VERIFY', error: `FLAC verification failed for ${path.basename(bad)}`, flacFiles, expectedTracks, completedTracks: flacFiles.length };
  return { ok: true, flacFiles, expectedTracks, completedTracks: flacFiles.length };
}

export function classifyAbcdeFailure(paths: JobPaths): ClassifiedAbcdeFailure {
  const text = [safeRead(paths.stdoutLog), safeRead(paths.stderrLog)].join('\n').toLowerCase();
  const hasAny = (...needles: string[]) => needles.some((needle) => text.includes(needle));
  if (hasAny('temporary failure in name resolution', "can't connect", 'network is unreachable', 'connection timed out')) {
    return { failureType: 'FAILED_METADATA', reason: 'metadata lookup failed due to network/DNS error' };
  }
  if (text.includes('musicbrainz') && hasAny('failed', 'no matches', 'not found', 'abort')) {
    return { failureType: 'FAILED_METADATA', reason: 'musicbrainz metadata lookup failed' };
  }
  if (hasAny('medium not present', 'tray open', 'not ready:medium', 'no medium')) {
    return { failureType: 'FAILED_INTERRUPTED', reason: 'drive reported medium removed or tray open' };
  }
  if (hasAny('scsi_read', 'l-ec uncorrectable', 'medium error', 'i/o error', 'input/output error', 'read error', 'cdparanoia')) {
    return { failureType: 'FAILED_READ', reason: 'disc read error reported by drive/cdparanoia' };
  }
  if (hasAny('flac', 'encode', 'encoder', 'tagging')) {
    return { failureType: 'FAILED_ENCODE', reason: 'encoding or tagging failed' };
  }
  return { failureType: 'UNKNOWN_ERROR', reason: 'abcde failed with an unclassified error' };
}

function pathHasFileCollision(src: string, dest: string): boolean {
  if (!existsSync(dest)) return false;
  const srcStat = statSync(src);
  const destStat = statSync(dest);
  if (srcStat.isFile()) return destStat.isFile() || destStat.isDirectory();
  if (!srcStat.isDirectory()) return true;
  if (!destStat.isDirectory()) return true;
  return readdirSync(src).some((entry) => pathHasFileCollision(path.join(src, entry), path.join(dest, entry)));
}

function uniqueSiblingPath(dest: string, suffix: string): string {
  const parsed = path.parse(dest);
  for (let i = 0; i < 100; i++) {
    const candidate = path.join(parsed.dir, `${parsed.name}${suffix}${i === 0 ? '' : ` ${i}`}${parsed.ext}`);
    if (!existsSync(candidate)) return candidate;
  }
  throw new Error(`could not find unique publish path for ${dest}`);
}

function publishNode(src: string, requestedDest: string, collisionSuffix: string, depth: number): void {
  const srcStat = statSync(src);
  if (srcStat.isFile()) {
    if (existsSync(requestedDest)) throw new Error(`refusing to overwrite existing library file ${requestedDest}`);
    mkdirSync(path.dirname(requestedDest), { recursive: true });
    renameSync(src, requestedDest);
    return;
  }
  if (!srcStat.isDirectory()) return;

  let dest = requestedDest;
  if (depth > 0 && pathHasFileCollision(src, requestedDest)) {
    dest = uniqueSiblingPath(requestedDest, collisionSuffix);
  }
  mkdirSync(dest, { recursive: true });
  for (const entry of readdirSync(src)) {
    publishNode(path.join(src, entry), path.join(dest, entry), collisionSuffix, depth + 1);
  }
  rmSync(src, { recursive: true, force: true });
}

function safeRead(file: string): string { try { return readFileSync(file, 'utf8'); } catch { return ''; } }

export function sanitizePathSegment(input: string): string {
  const withoutControls = [...input.normalize('NFC')].filter((ch) => {
    const code = ch.codePointAt(0) ?? 0;
    return code > 31 && code !== 127;
  }).join('');
  const cleaned = withoutControls
    .replace(/[\\/]+/g, ' ')
    .replace(/\.\.+/g, '.')
    .trim()
    .replace(/^\.+$/, '')
    .slice(0, 160);
  return cleaned.length > 0 ? cleaned : 'Unknown';
}

function readPersistedJobMetadata(paths: JobPaths): PersistedJobMetadata {
  try {
    const parsed = JSON.parse(readFileSync(path.join(paths.workDir, 'job.json'), 'utf8')) as PersistedJobMetadata;
    return parsed && typeof parsed === 'object' ? parsed : {};
  } catch { return {}; }
}

export function preparePublishTree(paths: JobPaths): void {
  rmSync(paths.publishDir, { recursive: true, force: true });
  mkdirSync(paths.publishDir, { recursive: true });
  for (const file of listFiles(paths.stagingDir, '.flac')) {
    const rel = path.relative(paths.stagingDir, file);
    if (rel.startsWith('..') || path.isAbsolute(rel)) throw new Error(`invalid staged path ${rel}`);
    const safeRel = rel.split(path.sep).map(sanitizePathSegment).join(path.sep);
    const dest = path.join(paths.publishDir, safeRel);
    mkdirSync(path.dirname(dest), { recursive: true });
    cpSync(file, dest, { force: false, errorOnExist: true });
  }
}

export function atomicPublish(paths: JobPaths, libraryDir: string): void {
  preparePublishTree(paths);
  const topEntries = readdirSync(paths.publishDir);
  if (topEntries.length === 0) throw new Error('nothing to publish');
  mkdirSync(libraryDir, { recursive: true });

  // /work and /music may be different mounts. Cross-device rename is impossible,
  // so copy to a hidden staging directory inside the final library filesystem,
  // then perform same-filesystem renames into the visible library paths.
  const libraryStaging = path.join(libraryDir, `.rippy-staging-${path.basename(paths.workDir)}`);
  rmSync(libraryStaging, { recursive: true, force: true });
  mkdirSync(libraryStaging, { recursive: true });
  try {
    for (const entry of topEntries) {
      cpSync(path.join(paths.publishDir, entry), path.join(libraryStaging, entry), {
        recursive: true,
        force: false,
        errorOnExist: true,
      });
    }
    const collisionSuffix = ` [${path.basename(paths.workDir).slice(0, 8)}]`;
    for (const entry of topEntries) {
      publishNode(path.join(libraryStaging, entry), path.join(libraryDir, entry), collisionSuffix, 0);
    }
    rmSync(libraryStaging, { recursive: true, force: true });
  } catch (err) {
    rmSync(libraryStaging, { recursive: true, force: true });
    throw err;
  }
}

export function markInterruptedJobs(workRoot: string): string[] {
  if (!existsSync(workRoot)) return [];
  const marked: string[] = [];
  for (const entry of readdirSync(workRoot)) {
    const dir = path.join(workRoot, entry);
    if (!statSync(dir).isDirectory()) continue;
    const running = path.join(dir, 'RUNNING');
    const terminal = ['COMPLETED', 'FAILED', 'CANCELLED'].some((name) => existsSync(path.join(dir, name)));
    if (existsSync(running) && !terminal) {
      rmSync(running, { force: true });
      writeFileSync(path.join(dir, 'FAILED_INTERRUPTED'), new Date().toISOString());
      marked.push(entry);
    }
  }
  return marked;
}
