import { existsSync, mkdirSync, readdirSync, readFileSync, renameSync, rmSync, statSync, writeFileSync, cpSync } from 'node:fs';
import path from 'node:path';
import { spawnSync } from 'node:child_process';

export type ArmFailureType = 'FAILED_READ' | 'FAILED_ENCODE' | 'FAILED_VERIFY' | 'FAILED_FINALIZE' | 'FAILED_METADATA' | 'FAILED_INTERRUPTED' | 'CANCELLED' | 'UNKNOWN_ERROR';

export interface TrackExpectation { discId?: string; expectedTracks: number; }
export interface JobPaths { workDir: string; stagingDir: string; publishDir: string; logDir: string; wavDir: string; abcdeConfig: string; stdoutLog: string; stderrLog: string; }
export interface ValidationResult { ok: boolean; failureType?: ArmFailureType; error?: string; flacFiles: string[]; expectedTracks: number; completedTracks: number; }

export function createJobPaths(workRoot: string, jobId: string): JobPaths {
  const safeJobId = jobId.replace(/[^a-zA-Z0-9_-]/g, '');
  const workDir = path.join(workRoot, safeJobId);
  return {
    workDir,
    stagingDir: path.join(workDir, 'staging'),
    publishDir: path.join(workDir, 'publish'),
    logDir: path.join(workDir, 'logs'),
    wavDir: path.join(workDir, 'wav'),
    abcdeConfig: path.join(workDir, 'abcde.conf'),
    stdoutLog: path.join(workDir, 'logs', 'abcde.stdout.log'),
    stderrLog: path.join(workDir, 'logs', 'abcde.stderr.log'),
  };
}

export function prepareFreshJob(paths: JobPaths): void {
  rmSync(paths.workDir, { recursive: true, force: true });
  mkdirSync(paths.stagingDir, { recursive: true });
  mkdirSync(paths.publishDir, { recursive: true });
  mkdirSync(paths.logDir, { recursive: true });
  mkdirSync(paths.wavDir, { recursive: true });
}

export function readTrackExpectation(device: string): TrackExpectation {
  const result = spawnSync('cd-discid', [device], { encoding: 'utf8', timeout: 5000 });
  if (result.status !== 0) return { expectedTracks: 0 };
  const parts = result.stdout.trim().split(/\s+/);
  const discId = parts[0] && /^[a-fA-F0-9]+$/.test(parts[0]) ? parts[0].toLowerCase() : undefined;
  const expectedTracks = parts[1] ? Number(parts[1]) : 0;
  return { ...(discId ? { discId } : {}), expectedTracks: Number.isFinite(expectedTracks) ? expectedTracks : 0 };
}

export function writeArmAbcdeConfig(paths: JobPaths, outputFormat: string): void {
  if (outputFormat.toLowerCase() !== 'flac') throw new Error('ARM-style audio pipeline only supports FLAC output');
  const config = [
    '# Generated by Rippymcripface for an isolated ARM-style audio job.',
    'CDDBMETHOD=musicbrainz',
    'INTERACTIVE=n',
    'CDDBLOCALRECURSIVE=n',
    'NOSUBMIT=y',
    'CDROMREADERSYNTAX=cdparanoia',
    'CDPARANOIA=cdparanoia',
    'CDDISCID=cd-discid',
    'OUTPUTTYPE=flac',
    'FLACENCODERSYNTAX=flac',
    'FLAC=flac',
    'PADTRACKS=y',
    'MAXPROCS=2',
    'ACTIONS=musicbrainz,read,encode,tag,move,clean',
    'CDPARANOIAOPTS="-z=100 -X"',
    'FLACOPTS="-8 -V"',
    `OUTPUTDIR=${shellQuote(paths.stagingDir)}`,
    `WAVOUTPUTDIR=${shellQuote(paths.wavDir)}`,
    "OUTPUTFORMAT='${ARTISTFILE}/${ALBUMFILE}/${TRACKNUM} - ${TRACKFILE}'",
    "VAOUTPUTFORMAT='Various Artists/${ALBUMFILE}/${TRACKNUM} - ${ARTISTFILE} - ${TRACKFILE}'",
    'ONETRACKOUTPUTFORMAT=$OUTPUTFORMAT',
    'VAONETRACKOUTPUTFORMAT=$VAOUTPUTFORMAT',
    '',
  ].join('\n');
  writeFileSync(paths.abcdeConfig, config, { encoding: 'utf8', mode: 0o600 });
}

function shellQuote(value: string): string { return `'${value.replace(/'/g, `'\\''`)}'`; }

export function listFiles(root: string, ext: string): string[] {
  if (!existsSync(root)) return [];
  const out: string[] = [];
  const walk = (dir: string): void => {
    for (const entry of readdirSync(dir)) {
      const full = path.join(dir, entry);
      const st = statSync(full);
      if (st.isDirectory()) walk(full);
      else if (st.isFile() && full.toLowerCase().endsWith(ext)) out.push(full);
    }
  };
  walk(root);
  return out.sort();
}

export function verifyFlac(file: string): boolean {
  const result = spawnSync('flac', ['-t', '-s', file], { encoding: 'utf8', timeout: 120_000 });
  return result.status === 0;
}

export function validateCompletedRip(paths: JobPaths, expectedTracks: number, abcdeExitCode: number | null): ValidationResult {
  const flacFiles = listFiles(paths.stagingDir, '.flac');
  if (abcdeExitCode !== 0) return { ok: false, failureType: classifyAbcdeFailure(paths), error: `abcde exited with code ${abcdeExitCode}`, flacFiles, expectedTracks, completedTracks: flacFiles.length };
  if (expectedTracks <= 0) return { ok: false, failureType: 'FAILED_METADATA', error: 'could not determine expected audio track count', flacFiles, expectedTracks, completedTracks: flacFiles.length };
  if (flacFiles.length !== expectedTracks) return { ok: false, failureType: 'FAILED_VERIFY', error: `expected ${expectedTracks} FLAC files but found ${flacFiles.length}`, flacFiles, expectedTracks, completedTracks: flacFiles.length };
  const bad = flacFiles.find((file) => !verifyFlac(file));
  if (bad) return { ok: false, failureType: 'FAILED_VERIFY', error: `FLAC verification failed for ${path.basename(bad)}`, flacFiles, expectedTracks, completedTracks: flacFiles.length };
  return { ok: true, flacFiles, expectedTracks, completedTracks: flacFiles.length };
}

function classifyAbcdeFailure(paths: JobPaths): ArmFailureType {
  const text = [safeRead(paths.stdoutLog), safeRead(paths.stderrLog)].join('\n').toLowerCase();
  if (text.includes('musicbrainz') && (text.includes('failed') || text.includes('no matches'))) return 'FAILED_METADATA';
  if (text.includes('encode') || text.includes('flac')) return 'FAILED_ENCODE';
  if (text.includes('scsi_read') || text.includes('cdparanoia') || text.includes('readtrack')) return 'FAILED_READ';
  return 'UNKNOWN_ERROR';
}

function safeRead(file: string): string { try { return readFileSync(file, 'utf8'); } catch { return ''; } }

export function sanitizePathSegment(input: string): string {
  const withoutControls = [...input.normalize('NFC')].filter((ch) => {
    const code = ch.codePointAt(0) ?? 0;
    return code > 31 && code !== 127;
  }).join('');
  const cleaned = withoutControls
    .replace(/[\\/]+/g, ' ')
    .replace(/\.\.+/g, '.')
    .trim()
    .replace(/^\.+$/, '')
    .slice(0, 160);
  return cleaned.length > 0 ? cleaned : 'Unknown';
}

export function preparePublishTree(paths: JobPaths): void {
  rmSync(paths.publishDir, { recursive: true, force: true });
  mkdirSync(paths.publishDir, { recursive: true });
  for (const file of listFiles(paths.stagingDir, '.flac')) {
    const rel = path.relative(paths.stagingDir, file);
    if (rel.startsWith('..') || path.isAbsolute(rel)) throw new Error(`invalid staged path ${rel}`);
    const safeRel = rel.split(path.sep).map(sanitizePathSegment).join(path.sep);
    const dest = path.join(paths.publishDir, safeRel);
    mkdirSync(path.dirname(dest), { recursive: true });
    cpSync(file, dest, { force: false, errorOnExist: true });
  }
}

export function atomicPublish(paths: JobPaths, libraryDir: string): void {
  preparePublishTree(paths);
  const topEntries = readdirSync(paths.publishDir);
  if (topEntries.length === 0) throw new Error('nothing to publish');
  mkdirSync(libraryDir, { recursive: true });
  for (const entry of topEntries) {
    const src = path.join(paths.publishDir, entry);
    const dest = path.join(libraryDir, entry);
    if (existsSync(dest)) throw new Error(`refusing to overwrite existing library path ${dest}`);
    renameSync(src, dest);
  }
}

export function markInterruptedJobs(workRoot: string): string[] {
  if (!existsSync(workRoot)) return [];
  const marked: string[] = [];
  for (const entry of readdirSync(workRoot)) {
    const dir = path.join(workRoot, entry);
    if (!statSync(dir).isDirectory()) continue;
    const running = path.join(dir, 'RUNNING');
    const terminal = ['COMPLETED', 'FAILED', 'CANCELLED'].some((name) => existsSync(path.join(dir, name)));
    if (existsSync(running) && !terminal) {
      rmSync(running, { force: true });
      writeFileSync(path.join(dir, 'FAILED_INTERRUPTED'), new Date().toISOString());
      marked.push(entry);
    }
  }
  return marked;
}
